### ISSUE TITLE
不会改

### ISSUE THREAD

**Issue by zl521368789** [abcz316/find_load_module#2]
编译好了，找到了，也看了源码，还是不会改..........

**Comment by samabl** [comment]
> 

大佬怎么编译的，能给个workflow吗

**Comment by jiangshilin6** [comment]
![Uploading image.png…]()

**Comment by jiek9999** [comment]
大佬，能给个编译好的exe吗

**Comment by yukiQLF** [comment]
> 大佬，能给个编译好的exe吗

嘿，你找到了吗？ 我正在找它

**Comment by abcz316** [comment]
Upgrade to one click automation has been completed
